performing Locally Linear Embedding 

In [2]:
'''
 used to reduce the number of dimensions in a dataset
 unsupervised method
 
 steps:
 1. Neighborhood Selection: k nearest neighbour
 2. Weight Matrix Construction: set of weights for each data point to express it as a linear combination of its neighbors
 3. Global Structure Preservation: find a lower-dimensional representation of the data that best preserves the local linear relationships.
 4. Output Embedding: LLE provides the final lower-dimensional representation of the data
 
'''

'\n used to reduce the number of dimensions in a dataset\n unsupervised method\n \n steps:\n 1. Neighborhood Selection: k nearest neighbour\n 2. Weight Matrix Construction: set of weights for each data point to express it as a linear combination of its neighbors\n 3. Global Structure Preservation: find a lower-dimensional representation of the data that best preserves the local linear relationships.\n 4. Output Embedding: LLE provides the final lower-dimensional representation of the data\n \n'

In [1]:
import numpy as np


In [3]:
# step:1 - Define the given points

X= np.array([[0,0],[2,0],
    [0,3],
    [1,1.5],
    [0.2,0.5]])

In [6]:
# step:2 - compute pairwise distances

n = X.shape[0]
distance = np.zeros((n,n))

for i in range (n):
    for j in range(n):
        distance[i, j] = np.sqrt(np.sum((X[i] - X[j])**2))
        
print(distance)

[[0.         2.         3.         1.80277564 0.53851648]
 [2.         0.         3.60555128 1.80277564 1.86815417]
 [3.         3.60555128 0.         1.80277564 2.50798724]
 [1.80277564 1.80277564 1.80277564 0.         1.28062485]
 [0.53851648 1.86815417 2.50798724 1.28062485 0.        ]]


In [ ]:
# Step 3: Nearest neighbours for X1
k = 2
i = 0 

neighbors_idx = np.argsort(distance[i])[1:k+1] # to avoid 0 distance
print("Nearest neighbours of X1:", neighbors_idx)

Nearest neighbours of X1: [4 3]


In [8]:
# Step 4: Construct local covariance
neighbors = X[neighbors_idx]
Z = (neighbors - X[i]).T    
C = Z.T @ Z
print("Local covariance matrix:\n", C)

Local covariance matrix:
 [[0.29 0.95]
 [0.95 3.25]]


In [9]:
# Step 5: Solve for weights
ones = np.ones(k)
w = np.linalg.solve(C, ones)
w = w / np.sum(w)  # affine constraint
print("Weights:", w)

Weights: [ 1.40243902 -0.40243902]


In [10]:
# Step 6: Reconstruct X1
x_reconstructed = np.dot(w, neighbors)
print("Reconstructed X1:", x_reconstructed)
print("Original X1:", X[i])

Reconstructed X1: [-0.12195122  0.09756098]
Original X1: [0. 0.]
